# Import other config fragments first

import = [
	"~/.config/alacritty/keybindings.toml",
	"~/.config/alacritty/font.toml",
	# Select one of the color schemes
	# "~/.config/alacritty/catppuccin-frappe.toml",
	# "~/.config/alacritty/catppuccin-latte.toml",
	# "~/.config/alacritty/catppuccin-macchiato.toml",
	"~/.config/alacritty/catppuccin-mocha.toml",
]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[env]
TERM = "xterm-256color"

[cursor]
style = "Block"
unfocused_hollow = true




# Mouse settings
[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Middle", action = "PasteSelection" },
]

[scrolling]
history = 40000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# Window settings
[window]
decorations = "Full"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

# Using 0/0 will fallback to window manager's recommended size.
# Hint: It always spawned at full height on arch linux, despite which lines was set
[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
