[font]
size = 10.0

[font.bold]
family = "JetBrainsMonoNerdFont"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMonoNerdFont"
style = "Light Italic"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Light"

[font.offset]
x = 0
y = 0
